from __future__ import annotations

from datetime import timedelta

from .domain import Candidate, Coordinates, ItineraryInput, WeatherContext


def fixture_weather(kind: str = "clear") -> WeatherContext:
    if kind.lower() == "rain":
        return WeatherContext(
            summary="Rain likely through the evening",
            temperature_f=64,
            precipitation_probability=82,
            is_wet=True,
        )
    return WeatherContext(
        summary="Partly sunny, comfortable later",
        temperature_f=72,
        precipitation_probability=12,
        is_wet=False,
    )


def fixture_candidates(request: ItineraryInput) -> list[Candidate]:
    start = request.start_at
    return [
        Candidate(
            id="fixture-roerich",
            name="Nicholas Roerich Museum",
            category="museum",
            mood_tags=("cultural", "relaxing", "low-energy"),
            coordinates=Coordinates(40.8029, -73.9683),
            duration_minutes=60,
            cost_low=0,
            cost_high=0,
            indoor=True,
            source_name="Fixture place",
            source_url="https://www.roerich.org/",
            confidence=0.90,
            estimate_notes=("Duration is a category-based estimate.",),
        ),
        Candidate(
            id="fixture-riverside",
            name="Riverside Park golden-hour walk",
            category="park",
            mood_tags=("outdoors", "relaxing", "date-night", "low-energy"),
            coordinates=Coordinates(40.8007, -73.9708),
            duration_minutes=50,
            cost_low=0,
            cost_high=0,
            indoor=False,
            source_name="Fixture place",
            source_url="https://www.nycgovparks.org/parks/riverside-park",
            confidence=0.88,
            estimate_notes=("Duration is a flexible walking estimate.",),
        ),
        Candidate(
            id="fixture-book-culture",
            name="Book Culture browse",
            category="bookstore",
            mood_tags=("productive", "cultural", "relaxing", "low-energy"),
            coordinates=Coordinates(40.8063, -73.9652),
            duration_minutes=45,
            cost_low=0,
            cost_high=18,
            indoor=True,
            source_name="Fixture place",
            source_url="https://www.bookculture.com/",
            confidence=0.82,
            estimate_notes=("Cost assumes browsing with an optional purchase.",),
        ),
        Candidate(
            id="fixture-trivia",
            name="Neighborhood trivia table",
            category="trivia",
            mood_tags=("social", "chaotic", "food-focused"),
            coordinates=Coordinates(40.7872, -73.9755),
            duration_minutes=85,
            cost_low=8,
            cost_high=18,
            indoor=True,
            source_name="Fixture city event",
            source_url=None,
            confidence=0.76,
            start_at=start + timedelta(minutes=55),
            end_at=start + timedelta(minutes=140),
            estimate_notes=("Food and drink cost is estimated.", "Verify event details before leaving."),
        ),
        Candidate(
            id="fixture-comedy",
            name="Basement stand-up showcase",
            category="comedy",
            mood_tags=("social", "date-night", "chaotic"),
            coordinates=Coordinates(40.7835, -73.9794),
            duration_minutes=75,
            cost_low=12,
            cost_high=20,
            indoor=True,
            source_name="Fixture city event",
            source_url=None,
            confidence=0.80,
            start_at=start + timedelta(minutes=120),
            end_at=start + timedelta(minutes=195),
            estimate_notes=("Ticket price is estimated.", "Verify event details before leaving."),
        ),
        Candidate(
            id="fixture-jazz",
            name="Early jazz set",
            category="music",
            mood_tags=("social", "date-night", "cultural"),
            coordinates=Coordinates(40.7797, -73.9802),
            duration_minutes=70,
            cost_low=15,
            cost_high=24,
            indoor=True,
            source_name="Fixture city event",
            source_url=None,
            confidence=0.78,
            start_at=start + timedelta(minutes=145),
            end_at=start + timedelta(minutes=215),
            estimate_notes=("Cover charge is estimated.", "Verify event details before leaving."),
        ),
        Candidate(
            id="fixture-dumplings",
            name="Hand-pulled noodles and dumplings",
            category="restaurant",
            mood_tags=("food-focused", "social", "date-night"),
            coordinates=Coordinates(40.7992, -73.9671),
            duration_minutes=55,
            cost_low=14,
            cost_high=24,
            indoor=True,
            source_name="Fixture place",
            source_url=None,
            confidence=0.75,
            estimate_notes=("Meal cost and duration are category-based estimates.",),
        ),
        Candidate(
            id="fixture-cafe",
            name="Window-seat cafe reset",
            category="cafe",
            mood_tags=("productive", "relaxing", "low-energy"),
            coordinates=Coordinates(40.7950, -73.9703),
            duration_minutes=45,
            cost_low=5,
            cost_high=12,
            indoor=True,
            source_name="Fixture place",
            source_url=None,
            confidence=0.74,
            estimate_notes=("Cafe cost and duration are category-based estimates.",),
        ),
        Candidate(
            id="fixture-dessert",
            name="Late-night cookie stop",
            category="dessert",
            mood_tags=("food-focused", "social", "date-night", "chaotic"),
            coordinates=Coordinates(40.7858, -73.9721),
            duration_minutes=25,
            cost_low=4,
            cost_high=9,
            indoor=True,
            source_name="Fixture place",
            source_url=None,
            confidence=0.72,
            estimate_notes=("Cost and duration are category-based estimates.",),
        ),
        Candidate(
            id="fixture-cathedral",
            name="Cathedral architecture loop",
            category="landmark",
            mood_tags=("cultural", "outdoors", "relaxing"),
            coordinates=Coordinates(40.8038, -73.9619),
            duration_minutes=45,
            cost_low=0,
            cost_high=0,
            indoor=None,
            source_name="Fixture place",
            source_url="https://www.stjohndivine.org/",
            confidence=0.80,
            estimate_notes=("Access and duration should be verified.",),
        ),
    ]

