/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode */
        get: operations["geocode_v1_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/itineraries/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_v1_itineraries_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Share */
        post: operations["create_share_v1_shares_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Share */
        get: operations["get_share_v1_shares__share_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CoordinatesSchema */
        CoordinatesSchema: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** CreateShareRequest */
        CreateShareRequest: {
            brief: components["schemas"]["GenerateRequest"];
            generation: components["schemas"]["GenerationResponse-Input"];
            /** Snapshot Token */
            snapshot_token: string;
            /** Selected Plan Id */
            selected_plan_id: string;
        };
        /** CreateShareResponse */
        CreateShareResponse: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Location Label */
            location_label: string;
            coordinates: components["schemas"]["CoordinatesSchema"];
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Available Minutes */
            available_minutes: number;
            /**
             * Budget Min
             * @default 0
             */
            budget_min: number;
            /** Budget Max */
            budget_max: number;
            /** Group Size */
            group_size: number;
            /**
             * Transport Mode
             * @enum {string}
             */
            transport_mode: "walk" | "bike" | "transit";
            /** Radius Miles */
            radius_miles: number;
            /**
             * Mood
             * @enum {string}
             */
            mood: "social" | "relaxing" | "outdoors" | "date-night" | "productive" | "chaotic" | "low-energy" | "cultural" | "food-focused";
            /**
             * Regeneration Seed
             * @default 0
             */
            regeneration_seed: number;
        };
        /** GenerationResponse */
        "GenerationResponse-Input": {
            weather: components["schemas"]["WeatherResponse"];
            /** Plans */
            plans: components["schemas"]["ItineraryPlanResponse-Input"][];
            /** Warnings */
            warnings: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /** Snapshot Token */
            snapshot_token?: string | null;
        };
        /** GenerationResponse */
        "GenerationResponse-Output": {
            weather: components["schemas"]["WeatherResponse"];
            /** Plans */
            plans: components["schemas"]["ItineraryPlanResponse-Output"][];
            /** Warnings */
            warnings: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /** Snapshot Token */
            snapshot_token?: string | null;
        };
        /** GeocodeResponse */
        GeocodeResponse: {
            /** Results */
            results: components["schemas"]["GeocodeResult"][];
            /** Warnings */
            warnings?: string[];
        };
        /** GeocodeResult */
        GeocodeResult: {
            /** Label */
            label: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Fixture Mode */
            fixture_mode: boolean;
            /** Sharing Enabled */
            sharing_enabled: boolean;
        };
        /** ItineraryPlanResponse */
        "ItineraryPlanResponse-Input": {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Score */
            score: number;
            /** Confidence */
            confidence: number;
            /** Total Minutes */
            total_minutes: number;
            /** Total Cost Low */
            total_cost_low: number;
            /** Total Cost High */
            total_cost_high: number;
            /** Steps */
            steps: components["schemas"]["TimelineStepResponse"][];
            /** Estimate Notes */
            estimate_notes: string[];
        };
        /** ItineraryPlanResponse */
        "ItineraryPlanResponse-Output": {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Score */
            score: number;
            /** Confidence */
            confidence: number;
            /** Total Minutes */
            total_minutes: number;
            /** Total Cost Low */
            total_cost_low: number;
            /** Total Cost High */
            total_cost_high: number;
            /** Steps */
            steps: components["schemas"]["TimelineStepResponse"][];
            /** Estimate Notes */
            estimate_notes: string[];
        };
        /** SharedBrief */
        SharedBrief: {
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Available Minutes */
            available_minutes: number;
            /** Budget Min */
            budget_min: number;
            /** Budget Max */
            budget_max: number;
            /** Group Size */
            group_size: number;
            /**
             * Transport Mode
             * @enum {string}
             */
            transport_mode: "walk" | "bike" | "transit";
            /** Radius Miles */
            radius_miles: number;
            /**
             * Mood
             * @enum {string}
             */
            mood: "social" | "relaxing" | "outdoors" | "date-night" | "productive" | "chaotic" | "low-energy" | "cultural" | "food-focused";
        };
        /** SharedItineraryResponse */
        SharedItineraryResponse: {
            /** Id */
            id: string;
            brief: components["schemas"]["SharedBrief"];
            generation: components["schemas"]["GenerationResponse-Output"];
            /** Selected Plan Id */
            selected_plan_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** TimelineStepResponse */
        TimelineStepResponse: {
            /** Candidate Id */
            candidate_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            coordinates: components["schemas"]["CoordinatesSchema"];
            /** Cost Low */
            cost_low: number;
            /** Cost High */
            cost_high: number;
            /** Confidence */
            confidence: number;
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string | null;
            /** Estimate Notes */
            estimate_notes: string[];
            travel_before: components["schemas"]["TravelLegResponse"];
        };
        /** TravelLegResponse */
        TravelLegResponse: {
            /** Mode */
            mode: string;
            /** Minutes */
            minutes: number;
            /** Distance Miles */
            distance_miles: number;
            /** From Label */
            from_label: string;
            /** To Label */
            to_label: string;
            /** Estimate Note */
            estimate_note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherResponse */
        WeatherResponse: {
            /** Summary */
            summary: string;
            /** Temperature F */
            temperature_f: number | null;
            /** Precipitation Probability */
            precipitation_probability: number;
            /** Is Wet */
            is_wet: boolean;
            /** Is Severe */
            is_severe: boolean;
            /** Source Name */
            source_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    geocode_v1_geocode_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_v1_itineraries_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_v1_shares_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateShareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_v1_shares__share_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedItineraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
